<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUpelmyd\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUpelmyd/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUpelmyd.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUpelmyd\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerUpelmyd\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Upelmyd',
    'container.build_id' => '8e7a2719',
    'container.build_time' => 1516209053,
));
