imports:
    - { resource: parameters.yml }

framework:
    secret: fixtures_factory
    validation: ~
    default_locale:  en
    session: ~

doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        unix_socket: /tmp/mysql.sock
        types: #this is about this line and line below
            json:     \Doctrine\DBAL\Types\StringType
    #orm:
    #    auto_generate_proxy_classes: "%kernel.debug%"
    #    auto_mapping: true
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            FixturesFactoryDemo:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/testapp/src/FixturesFactoryDemoBundle/Entity'
                prefix: 'Nietzscheson\FixturesFactoryDemo\Entity'
                alias: FixturesFactoryDemo