# This file is a "template" of what your parameters.yml file should look like
parameters:
   database_driver:   pdo_mysql
   database_host:     db
   database_port:     3306
   database_name:     fixtures
   database_user:     root
   database_password: root

   locale:            en

   secret:            ThisTokenIsNotSoSecretChangeIt